### ISSUE TITLE
Failed to skip ssl verification

### ISSUE THREAD

**Issue by tao-xinxiu** [push2cloud/push2cloud#2]
- **Version**: 1.0.0
- **Platform**: Ubuntu 14.04
- **Module**: push2cloud-cf-adapter:stageApp

Hello, I need to skip SSL verification to use my Cloud Foundry instance. I tried to add `"rejectUnauthorized": false` in `example/manifests/deployment.json` the `target` part. Now, the apps are successfully created, but it returns an error message during "stageApp":

```
push2cloud-cf-adapter:stageApp Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1055:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:580:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:412:38)
```

Is there any way I could skip SSL verification during "stageApp" ?

**Comment by michaelerne** [comment]
Hey there, thanks for reporting this issue.

We have identified the problem and will fix it within the next few days. 
Some details:
the `"rejectUnauthorized": false` is not correctly propagated to the `getLogWebSocket` function within the cf-adapter.

**Comment by michaelerne** [comment]
I just published a new version (1.0.5) of the push2cloud-cf-adapter on npm that should resolve the issue. Could you update to the latest dependencies and try again? Thanks

**Comment by tao-xinxiu** [comment]
Thank you for your prompt reply.  I redid `npm install` with specifying "push2cloud-cf-adapter": "1.0.5" in package.json, and then retried the command `node_modules/.bin/p2c exec ./node_modules/push2cloud-cf-workflows/blueGreen.js`, but it returned the same error.

**Comment by michaelerne** [comment]
Could you try to remove the `node_modules` folder completely and do a complete reinstall? We had issues in the past with "upgrading" certain modules with the way you described.

**Comment by tao-xinxiu** [comment]
Issue fixed. Thank you very much.
