### ISSUE TITLE
How to specify application bits path

### ISSUE THREAD

**Issue by tao-xinxiu** [push2cloud/push2cloud#3]
- **Version**: 1.0.0
- **Platform**: Ubuntu 14.04
- **Module**: application manifest

Hello, I am trying to use push2cloud to deploy a Java application. I don't find how to specify the bits path in the application json manifest. Whether it's possible ?

**Comment by adrai** [comment]
Hi!
What do you mean by bits path?
We have other examples here: https://github.com/push2cloud/example-apps/tree/master/hot-coal/apps, perhaps this may help...

**Comment by tao-xinxiu** [comment]
Yes, which is defined as `path` attribute in Cloud Foundry `manifest.yml`. It seems to me that the whole app directory will be packaged and uploaded in push2cloud, but with the java-buildpack, we are supposed to upload only the .jar or .war file.

**Comment by adrai** [comment]
Ok... we see the problem...
We will try to solve this problem by "**push2cloudify**" ;-) a java sample app like this: https://github.com/swisscom/cf-sample-app-java
stay tuned

**Comment by michaelerne** [comment]
The promised java app is here: 
https://github.com/push2cloud/example-apps/tree/master/java

We made some changes throughout p2c to enable the path functionality, be sure to update/reinstall your node_modules. 

Please let us know if that worked for you.

**Comment by tao-xinxiu** [comment]
It worked. Thanks for the quick fix. ;-)

**Comment by michaelerne** [comment]
Always happy to help 👍
