### ISSUE TITLE
GIF in the readme is all messed up in firefox. Works fine on other browsers. 

### ISSUE THREAD

**Issue by dharmeshkakadia** [push2cloud/push2cloud#4]
- **Version**:
- **Platform**:
- **Module**:
- **Node**:
- **Npm**:

**Comment by adrai** [comment]
Thx, we're going to look at it in the next days.

**Comment by michaelerne** [comment]
I think our GIF triggered https://bugzilla.mozilla.org/show_bug.cgi?id=1234077.

Anyhow, new GIF is pushed that works in firefox 47.0.1.
